{
  "type": "log",
  "@timestamp": "2018-01-28T04:59:38Z",
  "tags": [
    "status",
    "info",
    "Sentinl"
  ],
  "pid": 21344,
  "message": "Error storing Alarm: [illegal_argument_exception] [message] is defined as an object in mapping [report_admin] but this name is already used for a field in other types :: {\"path\":\"/watcher_alarms-2018.01.28/report_admin\",\"query\":{},\"body\":\"{\\\"@timestamp\\\":\\\"2018-01-28T04:59:38.364Z\\\",\\\"watcher\\\":\\\"reporter_title\\\",\\\"level\\\":\\\"INFO\\\",\\\"message\\\":{},\\\"action\\\":\\\"report_admin\\\",\\\"payload\\\":{},\\\"report\\\":false}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"illegal_argument_exception\\\",\\\"reason\\\":\\\"[message] is defined as an object in mapping [report_admin] but this name is already used for a field in other types\\\"}],\\\"type\\\":\\\"illegal_argument_exception\\\",\\\"reason\\\":\\\"[message] is defined as an object in mapping [report_admin] but this name is already used for a field in other types\\\"},\\\"status\\\":400}\"}"
}
